---
version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
    environment:
      - DEFAULT_HOST=support.glocms.net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
    depends_on:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-railsserver:
    image: ghcr.io/zammad/zammad:6.4.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_DB: zammad_production
      POSTGRESQL_HOST: zammad-postgresql
      POSTGRESQL_USER: zammad
      POSTGRESQL_PASS: zammad
      REDIS_URL: redis://zammad-redis:6379
      ELASTICSEARCH_HOST: zammad-elasticsearch
      ELASTICSEARCH_PORT: 9200
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-postgresql
      - zammad-redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-nginx:
    image: ghcr.io/zammad/zammad:6.4.0
    restart: always
    command: ["zammad-nginx"]
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=support.glocms.net
      - LETSENCRYPT_HOST=support.glocms.net
      - LETSENCRYPT_EMAIL=gavinvermaak83@gmail.com
    depends_on:
      - zammad-railsserver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-postgresql:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
      POSTGRES_DB: zammad_production
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-redis:
    image: redis:6
    restart: always
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-scheduler:
    image: ghcr.io/zammad/zammad:6.4.0
    restart: always
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-railsserver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zammad-websocket:
    image: ghcr.io/zammad/zammad:6.4.0
    restart: always
    command: ["zammad-websocket"]
    depends_on:
      - zammad-railsserver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  zammad-storage:
  postgresql-data:
  redis-data:
  elasticsearch-data:
  nginx-certs:
  nginx-vhost:
